apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cntlm.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cntlm.name" . }}
    helm.sh/chart: {{ include "cntlm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cntlm.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cntlm.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: proxy
              containerPort: 3128
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
           - name: CNTLM_PROXY
             value: {{ .Values.cntlm.proxy }}
           {{ if .Values.cntlm.domain }}
           - name: CNTLM_DOMAIN
             value: {{ .Values.cntlm.domain }}
           {{ end }}
           {{ if .Values.cntlm.username }}
           - name: CNTLM_USERNAME
             value: {{ .Values.cntlm.username }}
           {{ end }}
           {{ if .Values.cntlm.passlm }}
           - name: CNTLM_PASSLM
             valueFrom:
               secretKeyRef:
                 name: {{ include "cntlm.fullname" . }}-secret
                 key: cntlm_passlm
           {{ end }}
           {{ if .Values.cntlm.passnt }}
           - name: CNTLM_PASSNT
             valueFrom:
               secretKeyRef:
                 name: {{ include "cntlm.fullname" . }}-secret
                 key: cntlm_passnt
           {{ end }}
           {{ if .Values.cntlm.passntlmv2 }}
           - name: CNTLM_PASSNTLMV2
             valueFrom:
               secretKeyRef:
                 name: {{ include "cntlm.fullname" . }}-secret
                 key: cntlm_passntlmv2
           {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
