apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cntlm.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "cntlm.name" . }}
    helm.sh/chart: {{ include "cntlm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  {{ if .Values.cntlm.passlm }}
  cntlm_passlm: {{ .Values.cntlm.passlm }}
  {{ end }}
  {{ if .Values.cntlm.passnt }}
  cntlm_passnt: {{ .Values.cntlm.passnt }}
  {{ end }}
  {{ if .Values.cntlm.passntlmv2 }}
  cntlm_passntlmv2: {{ .Values.cntlm.passntlmv2 }}
  {{ end }}
